image: /home/dario/Dokumente/projects/robofetz/robofetz_as/src/utils/map/map_robofetz.png
resolution: 0.006
origin: [-0.7, -0.7, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25
mode: "trinary"
