map_server:
  ros__parameters:
    yaml_filename: "maps/my_arena.yaml"
    topic_name: "map"
    frame_id: "map"
    use_sim_time: false
    save_map_timeout: 2000
    
amcl:
  ros__parameters:
    use_map_topic: true
    first_map_only: true
    
global_costmap:
  ros__parameters:
    static_layer:
      map_topic: /map