# arena_camera_ros_config.yaml
/**:
  ros__parameters:
    camera: "\\_SB_.PCI0.XHC_.RHUB.HS03-3:1.0-32e4:0144" 
    format: "MJPEG" #needed for 60 fps
    width: 800
    height: 600
    role: "video"
    frame_id: "arena_camera_optical"
    camera_info_url: "package://arena_perception/config/arena_camera_info_600p.yaml"