image_width: 800
image_height: 600

camera_name: GlobalShutterCamera_GlobalS___SB__PCI0_XHC__RHUB_HS03_3_1_0_32e4_0144_800x600

camera_matrix:
  rows: 3
  cols: 3
  data: [452.2678061940432, 0.0, 368.1645110430599, 0.0, 452.30801580542106, 334.3080935134087, 0.0, 0.0, 1.0]

distortion_model: "fisheye"

distortion_coefficients:
  rows: 1
  cols: 4
  data: [-0.0466126520926349, 0.004174590878308579, -0.007936249167845362, 0.002278112329977697]

rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

projection_matrix:
  rows: 3
  cols: 4
  data: [452.2678061940432, 0.0, 368.1645110430599, 0.0, 0.0, 452.30801580542106, 334.3080935134087, 0.0, 0.0, 0.0, 1.0, 0.0]
